### ISSUE TITLE
Failsafe server connection

### ISSUE THREAD

**Issue by mustakimur** [Sumitsahu896/fileserver_rust#2]
I will recommend to change the following code with failsafe choice:
```rust
let listener = TcpListener::bind("127.0.0.1:2000") // client to connect to this port : 2000
            .expect("Unable to bind");      // return listener or panic
```

As following:
```rust
let addrs = [
        SocketAddr::from(([127, 0, 0, 1], 2000)),
        SocketAddr::from(([127, 0, 0, 1], 7070)),
    ];
    let listener = TcpListener::bind(&addrs[..])..expect("Unable to bind");
```
You can print the connected IP and port so that client can manually input IP and port on its side.

**Comment by dianestephens** [comment]
File server listen port options added as suggested.  If port 2000 is unavailable, port 7070 will be used.  User must enter the correct port number to connect.
