### ISSUE TITLE
matching commands recommendation

### ISSUE THREAD

**Issue by mustakimur** [Sumitsahu896/fileserver_rust#3]
The following code will only enforce hardcoded command:
```rust
"search"
                        if is_authenticated
                              && args.len() > 4
                              && args[1] == "-f"
                              && args.iter().any(|i| i == "-s") =>
```

Instead of that, more user-friendly option will be:
1. match only search.
2. if matched, check for valid arguments
3. if valid arguments are not provided, show user helpful suggestion.

**Comment by dianestephens** [comment]
Changes made to provide more informative messages to user.  Client will not send user commands to server without authentication and proper command syntax.  Server sends informative messages back to client for remaining situations.    Thanks for the good suggestion.
