### ISSUE TITLE
use code formatter

### ISSUE THREAD

**Issue by mustakimur** [Sumitsahu896/fileserver_rust#4]
I will recommend you to use rust code formatted. If you are using MS code editor, the following works great.
https://marketplace.visualstudio.com/items?itemName=rust-lang.rust

Here is a difference between your code and your formatted code:
![image](https://user-images.githubusercontent.com/1774620/116175621-a79d8180-a6de-11eb-93e4-96d1eeebb9b4.png)
![image](https://user-images.githubusercontent.com/1774620/116175683-cef44e80-a6de-11eb-8750-38215cbaf754.png)

**Comment by dianestephens** [comment]
Thanks for reporting the issue.  Used Rust formatter on the code.
